name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Set up Docker
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # 3. Log in to Docker Hub using repository secrets now it should work
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      # 4. Build the Docker image
      - name: Build Docker image
        run: |
          docker build -t vishalsingh81/wisecow:latest .

      # 5. Push the Docker image to Docker Hub
      - name: Push Docker image
        run: |
          docker push vishalsingh81/wisecow:latest

